[tool.black]
target-version = ['py38']

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
float_to_top = true

[tool.mypy]
ignore_missing_imports = true
